// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGlWfgToifWthmLGjwmD-HvAOZ5MTEc4w',
    appId: '1:449382666502:web:98f35111c0a5eafa97ce87',
    messagingSenderId: '449382666502',
    projectId: 'omnisense-aa843',
    authDomain: 'omnisense-aa843.firebaseapp.com',
    storageBucket: 'omnisense-aa843.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgJIPw5F0l2hjts1_S5Sa-ZsAjmSeUKA',
    appId: '1:449382666502:android:e28af1f9f024c4d097ce87',
    messagingSenderId: '449382666502',
    projectId: 'omnisense-aa843',
    storageBucket: 'omnisense-aa843.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGlWfgToifWthmLGjwmD-HvAOZ5MTEc4w',
    appId: '1:449382666502:web:3702761313ad3be297ce87',
    messagingSenderId: '449382666502',
    projectId: 'omnisense-aa843',
    authDomain: 'omnisense-aa843.firebaseapp.com',
    storageBucket: 'omnisense-aa843.firebasestorage.app',
  );
}
